"""
app.py — Streamlit UI for a fast, accurate, free RAG document Q&A tool.

Retrieval (finding relevant chunks) runs locally and free.
Answer generation uses the Groq API — fast, and free for this kind of usage.

Run with:
    streamlit run app.py

Needs a free Groq API key — see README for setup, or paste it in the sidebar.
"""

import os
import tempfile

import streamlit as st
from rag_engine import RAGEngine

st.set_page_config(page_title="Document Q&A (Groq RAG)", page_icon="📄", layout="wide")

st.title("📄 Document Q&A")
st.caption(
    "Upload PDFs (contracts, briefs, portfolios, anything) and ask questions about them. "
    "Retrieval runs locally; answers are generated by Groq — fast and free."
)


@st.cache_resource
def get_engine():
    return RAGEngine()


engine = get_engine()

with st.sidebar:
    st.header("🔑 API key")
    api_key_input = st.text_input(
        "Groq API key",
        type="password",
        value=engine._api_key or "",
        help="Free — get one at console.groq.com/keys, no credit card needed. Stored only for this session — never written to disk.",
    )
    if api_key_input and api_key_input != engine._api_key:
        engine.set_api_key(api_key_input)

    if not engine.has_api_key():
        st.warning("Add your free Groq API key above to ask questions.")

    st.divider()
    st.header("📁 Knowledge base")

    uploaded_files = st.file_uploader(
        "Upload PDF(s)", type=["pdf"], accept_multiple_files=True
    )

    if uploaded_files:
        if st.button("➕ Add to knowledge base", use_container_width=True):
            with st.spinner("Reading and indexing PDFs..."):
                for f in uploaded_files:
                    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                        tmp.write(f.read())
                        tmp_path = tmp.name
                    try:
                        n_chunks = engine.add_document(tmp_path, f.name)
                        st.success(f"Added **{f.name}** ({n_chunks} chunks)")
                    finally:
                        os.remove(tmp_path)

    st.divider()
    st.metric("Indexed chunks", len(engine.chunks))

    indexed_files = sorted({s[0] for s in engine.sources})
    if indexed_files:
        st.write("**Files in knowledge base:**")
        for fn in indexed_files:
            st.write(f"- {fn}")
    else:
        st.write("_No documents indexed yet._")

    st.divider()
    if st.button("🗑️ Clear knowledge base", use_container_width=True):
        engine.clear_index()
        st.rerun()

st.divider()

query = st.text_input(
    "Ask a question about your documents:",
    placeholder="e.g. What's the payment schedule in the contract?",
)

if query:
    if len(engine.chunks) == 0:
        st.warning("Upload and add at least one PDF first (sidebar, left).")
    elif not engine.has_api_key():
        st.warning("Add your free Groq API key in the sidebar first.")
    else:
        with st.spinner("Thinking..."):
            try:
                answer, sources = engine.answer_question(query)
            except Exception as e:
                st.error(f"Something went wrong: {e}")
                answer, sources = None, []

        if answer:
            st.subheader("Answer")
            st.write(answer)

            if sources:
                with st.expander("📌 Sources used to answer this"):
                    for r in sources:
                        fn, idx = r["source"]
                        st.markdown(f"**{fn}** — chunk {idx} (relevance {r['score']:.2f})")
                        st.caption(r["text"][:300] + ("..." if len(r["text"]) > 300 else ""))